export const FILTER_ALL = 'FILTER/FILTER_ALL';
export const FILTER_ACTIVE = 'FILTER/FILTER_ACTIVE';
export const FILTER_COMPLETE = 'FILTER/FILTER_COMPLETE';

export const COMPLETED_CLEAR = 'APP/COMPLETED_CLEAR';
export const SET_ALL_TODO_TOGGLE = 'APP/SET_ALL_TODO_TOGGLE';

export const ADD_TODO = 'APP/ADD_TODO';
export const DELETE_TODO = 'APP/DELETE_TODO';
export const SET_TODO_COMPLETED = 'APP/SET_TODO_COMPLETED';
export const EDIT_TODO = 'APP/EDIT_TODO';
